spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: 'root'
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true


